### ISSUE TITLE
Requirements in the wrong format in metadata

### ISSUE THREAD

**Issue by ericmj** [inaka/hexer.mk#15]
The requirements in the package metadata is being published in the wrong format. If the take katana v0.2.20 as example the requirements are listed as `[{<<"xref_runner">>, <<"0.2.4">>}, {<<"inaka_aleppo">>, <<"0.9.5">>}]` but the should be in this format:

``` erlang
[{<<"xref_runner">>, [
  {<<"app">>, <<"xref_runner">>},
  {<<"requirement">>, <<"0.2.4">>},
  {<<"optional">>, false}]},
 {<<"inaka_aleppo">>, [
  {<<"app">>, <<"inaka_aleppo">>},
  {<<"requirement">>, <<"0.9.5">>},
  {<<"optional">>, false}]}
]
```

Specification: https://github.com/hexpm/specifications/blob/master/package_metadata.md

EDIT: I also notice that all hexer published packages I can find are using strict version requirements such as "0.2.4". Since hex is semver I recommend using version ranges instead, such as ">= 0.2.0 and < 0.3.0" or "~> 0.2.0".

**Comment by elbrujohalcon** [comment]
The problem with using semver is that I'm pretty sure erlang.mk can't handle it yet. We'll see if/when ninenines/erlang.mk#495 gets implemented ;)

**Comment by elbrujohalcon** [comment]
Closing this issue since:
- requirements are created by hexer, I moved this issue to inaka/hexer#38
- Semver is dealt with in #16
