### ISSUE TITLE
Add a new dependency fetcher called hexpm to replace hex

### ISSUE THREAD

**Issue by jfacorro** [inaka/hexer.mk#17]
In this new `hex.pm` fetcher, allow users to specify the name of the package (which can be different than the associated application):

In the following example `aleppo` is the name of the application and `inaka_aleppo` the package:

```
DEPS = aleppo
dep_aleppo = hexpm inaka_aleppo 0.9.9
```

**Comment by elbrujohalcon** [comment]
Will be implemented in ninenines/erlang.mk#497
