### ISSUE TITLE
Failed to push repository

### ISSUE THREAD

**Issue by mmmries** [inaka/hexer.mk#21]
I'm working with the [hut](https://github.com/tolbrino/hut) project to try to make it [available on hex.pm](https://github.com/tolbrino/hut/issues/2).

I tried to load hexer `1.1.0` into the project and do a `make hex-publish`, but I'm getting

```
Error: {400,#{<<"message">> => <<"Bad request">>,<<"status">> => 400}}
```

Is there any way for me to debug what is going wrong with this publishing?

**Comment by elbrujohalcon** [comment]
Maybe @ericmj can give us some insight...

**Comment by elbrujohalcon** [comment]
Would you mind sharing the full output of `make hex-publish`?

**Comment by mmmries** [comment]
Here's the full output. I know that hex recently changed from using `authors` to using `maintainers` as the way to list project contributors. Just not sure how to debug this without being able to see the full request.

```
L422-MRies:hut mmmries$ make hex-publish
make[1]: Nothing to be done for `noop'.
Publishing...
Publishing hut v1.1.0

  Dependencies:

  Included files:
    src/hut.app.src
    include/hut.hrl
    Makefile
    erlang.mk
    README.md
    LICENSE
Before publishing, please read Hex CoC: https://hex.pm/docs/codeofconduct
Proceed? [Y/n]: y
Error: {400,#{<<"message">> => <<"Bad request">>,<<"status">> => 400}}
Usage: hexer [-h] [-v] [command]

  -h, --help     Show this help information.
  -v, --version  Show the version of this tool.

Commands:

  user.auth      Generate API key by providing username and password.
  user.register  Register new user.
  publish        Publish package in hex.pm.
  publish.docs    Publish docs in hex.pm.
```

**Comment by ericmj** [comment]
Hard to say without seeing the actual request. Bad request can happen for a number of reasons, invalid encoding, missing parameters etc.

**Comment by elbrujohalcon** [comment]
@ericmj I recall you have access to the logs. Isn't there anything reported about Hut?

**Comment by ericmj** [comment]
We only log server failures unfortunately, this is a client failure.

On Sun, Feb 21, 2016 at 6:17 PM, Brujo Benavides notifications@github.com
wrote:

> @ericmj https://github.com/ericmj I recall you have access to the logs.
> Isn't there anything reported about Hut?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/inaka/hexer.mk/issues/21#issuecomment-186862249.

## 

Eric Meadows-Jönsson

**Comment by elbrujohalcon** [comment]
@ericmj Would it be possible for you then to tweak that API a little bit to return the reason of the bad request on the `message` field instead of just `"Bad Request"`?

**Comment by elbrujohalcon** [comment]
@mmmries can you try to publish again after reviewing/merging mmmries/hut#1? Maybe some info was missing.

**Comment by mmmries** [comment]
@elbrujohalcon I just merged that PR and tried to publish again, but got the same error message.

```
L422-MRies:hut mmmries$ make hex-publish
make[1]: Nothing to be done for `noop'.
Publishing...
Publishing hut v1.1.0

  Dependencies:

  Included files:
    src/hut.app.src
    include/hut.hrl
    Makefile
    erlang.mk
    README.md
    LICENSE
Before publishing, please read Hex CoC: https://hex.pm/docs/codeofconduct
Proceed? [Y/n]: Y
Error: {400,#{<<"message">> => <<"Bad request">>,<<"status">> => 400}}
Usage: hexer [-h] [-v] [command]

  -h, --help     Show this help information.
  -v, --version  Show the version of this tool.

Commands:

  user.auth      Generate API key by providing username and password.
  user.register  Register new user.
  publish        Publish package in hex.pm.
  publish.docs    Publish docs in hex.pm.
```

**Comment by elbrujohalcon** [comment]
@mmmries curious… from my side (using inaka's hex.pm account):

``` bash
make[1]: Nothing to be done for `noop'.
 APP    hut.app.src
Publishing...
Publishing hut v1.1.0

  Dependencies:

  Included files:
    src/hut.app.src
    include/hut.hrl
    Makefile
    erlang.mk
    README.md
    LICENSE
Before publishing, please read Hex CoC: https://hex.pm/docs/codeofconduct
Proceed? [Y/n]:
Error: {403,
        #{<<"message">> => <<"account not authorized for this action">>,
          <<"status">> => 403}}
Usage: hexer [-h] [-v] [command]

  -h, --help     Show this help information.
  -v, --version  Show the version of this tool.

Commands:

  user.auth      Generate API key by providing username and password.
  user.register  Register new user.
  publish        Publish package in hex.pm.
  publish.docs    Publish docs in hex.pm.
```

@ericmj why can't I publish it?

**Comment by ericmj** [comment]
It's hard for us to add reason to every possible bad request.

**Comment by elbrujohalcon** [comment]
Ok, @ericmj. Any chance you can help us with this specific one?

**Comment by ericmj** [comment]
You can't publish it because you are not the owner of the package. I will delete it so you can publish.

EDIT: Deleted.

**Comment by elbrujohalcon** [comment]
woah, @ericmj … I didn't want that deletion to happen. Haha… anyway, now I'm on `"Bad Request"`-land as well.

**Comment by ericmj** [comment]
@elbrujohalcon The package didn't have any value as it was not anyway. We can delete again when the proper owner can publish.

**Comment by elbrujohalcon** [comment]
oh, excellent, then

**Comment by elbrujohalcon** [comment]
@ericmj can the error be that the version we're providing is `"v1.1.0\n"`?

**Comment by ericmj** [comment]
Yes, it needs to be a valid semver version.

**Comment by elbrujohalcon** [comment]
Fixed that. Still having issues. We'll keep you posted.

**Comment by elbrujohalcon** [comment]
@ericmj thank you, man!
@mmmries that was it, you need a proper semver version number, not `v1.1.0` (which is the latest tag, which is what you get from you using `{vsn, git}` on your app.src).

@ericmj please delete the package now, so @mmmries can upload it himself

**Comment by ericmj** [comment]
Deleted.

@elbrujohalcon Btw, you should add mix to the list of build tools since mix can build erlang.mk packages.

**Comment by mmmries** [comment]
@elbrujohalcon and @ericmj thanks! You are both going way beyond making good tools. :heart: :heart: :blue_heart: :green_heart: :yellow_heart: :heart: :blue_heart: :green_heart: :yellow_heart: :heart: :blue_heart: :green_heart: :yellow_heart: :blue_heart: :green_heart: :yellow_heart: 

I think I got it all published now
